name: Daily Update Tracker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

env:
  innoextract_version: 1.9
  arch: amd64

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update trackers_all.txt
        shell: pwsh
        run: |
          curl https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/chenjia404/CnTrackersList/master/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/main/trackerslist_tracker.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/Tunglies/TrackersList/main/all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/refs/heads/main/trackerslist_combine.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/refs/heads/main/trackerslist_combine_aria2.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/refs/heads/main/trackerslist_exclude.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/refs/heads/main/trackerslist_exclude_aria2.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/refs/heads/main/trackerslist_tracker.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/hezhijie0327/Trackerslist/refs/heads/main/trackerslist_tracker_aria2.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/ATaria2_all.txt >> trackers_all.txt
          curl https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/ATline_all.txt >> trackers_all.txt
          sort trackers_all.txt | uniq > tmp.txt
          mv tmp.txt trackers_all.txt

      - name: Test tracker availability
        shell: bash
        run: |
          > trackers_best.txt
          while IFS= read -r tracker; do
            if [[ "$tracker" == http* ]]; then
              # Check HTTP/HTTPS tracker
              if curl --connect-timeout 10 --max-time 10 -sI "$tracker" | grep -q "HTTP/"; then
                echo "$tracker" >> trackers_best.txt
              fi
            elif [[ "$tracker" == udp* ]]; then
              # Check UDP tracker
              tracker_url=$(echo "$tracker" | sed 's/udp:\/\///')
              if echo -n '' | nc -w 3 -u "${tracker_url%%:*}" "${tracker_url##*:}"; then
                echo "$tracker" >> trackers_best.txt
              fi
            fi
          done < trackers_all.txt

      - name: Commit and Push changes
        run: |
          echo $(date +'%Y%m%d') > date.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "$(date +'%Y%m%d')"
          git push -v --progress
